### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by pascalmail** [appsignal/rdkafka-ruby#101]
Hello, when I check the documentation of this gem at https://www.rubydoc.info/github/appsignal/rdkafka-ruby/Rdkafka, why is it still showing version 0.4.1 even though the one in master is 0.7.0 (https://github.com/appsignal/rdkafka-ruby/blob/master/lib/rdkafka/version.rb#L2)?

**Comment by thijsc** [comment]
Sorry, this keeps happening and I don't know why. Asking Rubydoc to clear their cache.
