### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by liyongxin** [appsignal/rdkafka-ruby#105]
I recently did some tests for performance, but the results were very unsatisfactory.

 My config file is as follows:
                        "batch.num.messages": 1000000,
                        "queue.buffering.max.ms": 15000,
                        "request.required.acks": 1,
                        "queue.buffering.max.messages":10000000,
                        "queue.buffering.max.kbytes": 4000000,
                        "socket.keepalive.enable": true,
                        "socket.send.buffer.bytes": 0,
                        "socket.blocking.max.ms": 2,
                        "message.max.bytes": 1000000000

The producer and kafka server are on the same network, so there is no network delay,
The test loads 400,000 pieces of data from a file, each piece of data is about 500 bytes, the average transmission time of the test results is 35s, and only more than 10,000 pieces of data are processed per second, and I found from the trace log print that most of the time is used for data After processing, it will take very little time to send to Kafka after packaging into a MessageSet. Does anyone have experience in this area, please help

**Comment by liyongxin** [comment]
![image](https://user-images.githubusercontent.com/7601142/72117955-7d5d6e80-338a-11ea-9bf1-58dc47d64737.png)
This is the log of librdkafka when generating the local message queue. About 10,000 pieces of data are generated every second. My configuration "queue.buffering.max.ms": 15000, so about 144544 pieces of data in 15 seconds. , So I want to know why the data processing takes so long, and the real problem lies

**Comment by liyongxin** [comment]
@gaffneyc @thijsc @nurse @MadBomber

**Comment by thijsc** [comment]
This looks like it's part of the internal operations of librdkafka, so think this question should be asked over in https://github.com/edenhill/librdkafka

Do you think the Ruby wrapper part has influence on the performance issue you see?
