### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by yosiat** [appsignal/rdkafka-ruby#111]
Hi!

Is it possible to release a new version? The last version was released on September according to RubyGems.

We are currently using the master version (because of https://github.com/appsignal/rdkafka-ruby/pull/86)

**Comment by thijsc** [comment]
I'll get a new version out shortly! Will update to 1.3.0 and bump the version.

**Comment by thijsc** [comment]
`0.8.0.beta.1` is out now, could you give it a spin?

**Comment by yosiat** [comment]
@thijsc I am running our CI with this version will update once it's finish

**Comment by yosiat** [comment]
@thijsc our CI passed with this version, looks like we are good to go

**Comment by thijsc** [comment]
Ok, I'm releasing it!
