### ISSUE TITLE
Producer Transaction Support

### ISSUE THREAD

**Issue by gremerritt** [appsignal/rdkafka-ruby#119]
Are there plans to add support for producer transactions to this library now that the functionality has landed in [librdkafka v1.4.0](https://github.com/edenhill/librdkafka/issues/1308)?

**Comment by thijsc** [comment]
We don't use that feature at the moment, so don't have an immediate need for it myself. If there is a lof of interest I'd consider working on it, but some other open issues would be first in line.

Is this something you'd be interested in picking up yourself?

**Comment by gremerritt** [comment]
We also don't have an immediate need for it (we have another solution for transactional guarantees in place already), but I have a hunch this could help us simply things considerably.

Not sure how much bandwidth I have at the moment, but in general yes I'd be open to working on this.

**Comment by thijsc** [comment]
Closing this, if anybody needs this functionality please do reopen :-)

**Comment by mensfeld** [comment]
@thijsc feel free to reopen. I will look into this in the upcoming weeks.

**Comment by mensfeld** [comment]
Getting back to this. I will create a new card for that. That's something I believe this lib should provide.
