### ISSUE TITLE
Handle EOF partition error properly in Consumer#each

### ISSUE THREAD

**Issue by jurriaan** [appsignal/rdkafka-ruby#12]
When trying this library I got the following error:

```
/app/vendor/bundle/ruby/2.4.0/gems/rdkafka-0.3.3/lib/rdkafka/consumer.rb:186:in `poll': Broker: No more messages (partition_eof) (Rdkafka::RdkafkaError)
	from /app/vendor/bundle/ruby/2.4.0/gems/rdkafka-0.3.3/lib/rdkafka/consumer.rb:207:in `block in each'
	from /app/vendor/bundle/ruby/2.4.0/gems/rdkafka-0.3.3/lib/rdkafka/consumer.rb:206:in `loop'
	from /app/vendor/bundle/ruby/2.4.0/gems/rdkafka-0.3.3/lib/rdkafka/consumer.rb:206:in `each'
```

I think the #each method should handle these errors (ignore them, or pass these notifications to the block). Currently the each method itself raises an exception when you reach the end of the partition which is probably not what people expect from this library.

**Comment by thijsc** [comment]
You can configure this behaviour with `enable.partition.eof`. I agree that it's counterintuitive that this happens with `each`.

I see two options:

* `each` could handle the execption and just keep going
* `each` could handle the execption and yield some kind of special eof message
* We could set `enable.partition.eof` to true by default

I think probably handling the exception makes the most sense. Not sure what is the nicest way to handle this, will think about it. What do you think?

**Comment by jurriaan** [comment]
I'm currently writing a Kafka Streams-like processor where I want to store the state in a compacted topic and read the state back into memory on start for which I need to know when I'm done. This could be accomplished by this special eof message. For most processors however this EOF messages is not needed so this should be configurable IMO.

**Comment by thijsc** [comment]
It is configurable already with `enable.partition.eof`, which is `true` by default in librdkafka..

**Comment by jurriaan** [comment]
@thijsc Ah yes, of course, there is no need for a configuration option in this library then, when the library receives an eof 'error' message it should yield some kind of special eof message. The `enable.partition.eof` flag can then be used to adjust this behaviour.

**Comment by thijsc** [comment]
Indeed. This issue is still open because I want to make the error handling nicer, but the configuration is good as is.

**Comment by thijsc** [comment]
By the way: If you want complete control over this you're probably better off calling `poll` in a loop.

**Comment by thijsc** [comment]
I'm still not sure how to make this better than it is, so decided to add a note in 45055f1b5c84480223d1785c4a306ff00015075b and close this. If anyone has good ideas about this one feel free to reopen.
