### ISSUE TITLE
admin api support

### ISSUE THREAD

**Issue by archfish** [appsignal/rdkafka-ruby#121]
Is there a plan to support admin api?
librdkafka has the function [rdkafka_admin.h](https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/src/rdkafka_admin.h)

**Comment by geoff2k** [comment]
@archfish are there particular parts of the Admin API beyond creating and deleting topics (#123) that you like to see?

**Comment by archfish** [comment]
> @archfish are there particular parts of the Admin API beyond creating and deleting topics (#123) that you like to see?

Creating and deleting topics has satisfied my needs. Great job!
