### ISSUE TITLE
Publishing fixed code

### ISSUE THREAD

**Issue by jameswalkerdine** [appsignal/rdkafka-ruby#140]
Hello!

We've just hit a problem with the code, that has been fixed ([here](https://github.com/appsignal/rdkafka-ruby/commit/16a4497f59f4d369ebfb4ad0784161400fd96424#diff-74e6cbec6778f9341481738cbc590cdebd82852eb8b5eef48ead50f0984f74d7L19)), but the change is not published and that prevents us from progressing to use the library as-is.

The last release (due to Rubygems) was made on 2nd June, but the fix was introduced on June the 30th. Are you planning to prepare a release with the fix in place any time soon?

Thank you!

**Comment by thijsc** [comment]
I've just pushed out `0.8.1`. Sorry for the delay! It took me a long time to move over to a different CI setup.
