### ISSUE TITLE
CI builds are not running for some pull requests

### ISSUE THREAD

**Issue by geoff2k** [appsignal/rdkafka-ruby#147]
#141 introduced Semaphore CI, but of the currently open pull requests, only one (#142) appears to have triggered a check (build) in the new CI infrastructure:

https://appsignal.semaphoreci.com/workflows/5ab5270e-7077-4580-b337-fe1cf750091f

@thijsc is it possible that the new CI will only authorize builds that originate from users within the appsignal organization?

**Comment by thijsc** [comment]
I tweaked the settings in the meantime.
