### ISSUE TITLE
Fluentd buffer queue becomes full when unknown topic error occurred

### ISSUE THREAD

**Issue by baosenle** [appsignal/rdkafka-ruby#149]
1. Scenes
   Fluentd use rdkafka plugin to send log records to kafka

2. Configs
   allow.auto.create.topics : false

3. Result
   When unknown topic error occurred, plugins continue to fail writing buffer chunks.
   Cause the normal block behind the queue to be blocked

4. My suggestions
   Can you encapsulate such a common error (unknown topic error), give the user a configuration item, when such an error occurs, whether to discard the log records，does not affect the sending of subsequent log records.

Thanks!

**Comment by baosenle** [comment]
Or can we use the default topic key to process uknown topic error ?

`
rescue Kafka::UnknownTopicOrPartition
        if @use_default_for_unknown_topic && topic != @default_topic
          producer.shutdown if producer
          log.warn "'#{topic}' topic not found. Retry with '#{default_topic}' topic"
          topic = @default_topic
          retry
        end
        raise
      end
`

**Comment by thijsc** [comment]
rdkafka should raise an error in this case, you can catch that. Maybe this should be fixed in fluentd instead?
