### ISSUE TITLE
Segfault while consuming messages

### ISSUE THREAD

**Issue by lindgrenj6** [appsignal/rdkafka-ruby#150]
Hey all, 
Getting a segfault during consumer message processing. I haven't troubleshot C-extensions before, but if you need more logs than this I can provide it. 

The behavior is consistent with both 0.8.0 and 0.8.1, and I've tried install both versions 1.5.0 and 1.5.3 of librdkafka. 

It is a recent thing as well, all was working fine until today. 

```
/usr/share/gems/gems/rdkafka-0.8.0/lib/rdkafka/producer.rb:46: [BUG] Segmentation fault at 0x0000000000000274
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0115 e:000114 CFUNC  :rd_kafka_destroy
c:0020 p:0034 s:0110 e:000109 METHOD /usr/share/gems/gems/rdkafka-0.8.0/lib/rdkafka/producer.rb:46
c:0019 p:0009 s:0106 e:000105 METHOD /usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/kafka/client.rb:61
c:0018 p:0037 s:0102 e:000100 METHOD /usr/share/gems/gems/topological_inventory-providers-common-2.1.4/lib/topological_inventory/providers/common/operations/source.
c:0017 p:0012 s:0095 e:000094 METHOD /usr/share/gems/gems/topological_inventory-providers-common-2.1.4/lib/topological_inventory/providers/common/operations/source.
c:0016 p:0068 s:0090 e:000089 METHOD /usr/share/gems/gems/topological_inventory-providers-common-2.1.4/lib/topological_inventory/providers/common/operations/source.
c:0015 p:0156 s:0084 e:000083 METHOD /opt/satellite-operations/lib/topological_inventory/satellite/operations/source.rb:50
c:0014 p:0135 s:0075 e:000074 METHOD /opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb:85
c:0013 p:0007 s:0065 e:000064 BLOCK  /opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb:63
c:0012 p:0146 s:0061 e:000060 METHOD /usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/kafka/common.rb:91
c:0011 p:0014 s:0049 e:000048 BLOCK  /usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/kafka/topic.rb:22
c:0010 p:0017 s:0045 e:000044 BLOCK  /usr/share/gems/gems/rdkafka-0.8.0/lib/rdkafka/consumer.rb:434 [FINISH]
c:0009 p:---- s:0041 e:000040 CFUNC  :loop
c:0008 p:0005 s:0037 e:000036 METHOD /usr/share/gems/gems/rdkafka-0.8.0/lib/rdkafka/consumer.rb:431
c:0007 p:0091 s:0033 e:000032 METHOD /usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/kafka/topic.rb:21
c:0006 p:0031 s:0025 e:000024 METHOD /usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/client.rb:215
c:0005 p:0040 s:0019 e:000018 METHOD /opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb:62
c:0004 p:0005 s:0013 e:000012 BLOCK  /opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb:25 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :loop
c:0002 p:0006 s:0006 e:000005 BLOCK  /opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb:25 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]
```

Thank you for looking in advance, really appreciate it!

**Comment by geoff2k** [comment]
Would you mind posting a trace from the 0.8.1 gem as well?

**Comment by thijsc** [comment]
Is there some code you could share that triggers this?

**Comment by slemrmartin** [comment]
Hi, I'm sending logs:
- [log.txt](https://github.com/appsignal/rdkafka-ruby/files/5775615/log.txt)

and links to backtrace: 
- [/usr/share/gems/gems/manageiq-messaging-1.0.2/lib/manageiq/messaging/kafka/client.rb:61](https://github.com/ManageIQ/manageiq-messaging/blob/v1.0.2/lib/manageiq/messaging/kafka/client.rb#L61)
- [/usr/share/gems/gems/topological_inventory-providers-common-2.1.4/lib/topological_inventory/providers/common/operations/source.rb](https://github.com/RedHatInsights/topological_inventory-providers-common/blob/v2.1.4.freeze/lib/topological_inventory/providers/common/operations/source.rb)
- [/opt/satellite-operations/lib/topological_inventory/satellite/operations/source.rb](https://github.com/RedHatInsights/topological_inventory-satellite/blob/master/lib/topological_inventory/satellite/operations/source.rb)
- [/opt/satellite-operations/lib/topological_inventory/satellite/receptor/client/response_worker.rb](https://github.com/RedHatInsights/topological_inventory-satellite/blob/master/lib/topological_inventory/satellite/receptor/client/response_worker.rb)

**Comment by slemrmartin** [comment]
So it seems we found the cause of a problem: Inside of processing the kafka response we created and closed new publisher in the same thread and the close method probably causes segfault.

**Comment by lindgrenj6** [comment]
As my colleague @slemrmartin said, it looks like we had a double-close somewhere in our application due to conflicting usage between this one worker and the other's.

Going to close this as it makes sense to see a double-destroy causing a segfault. 

Thanks so much for taking the time to look @geoff2k and @thijsc.
