### ISSUE TITLE
gem installation shouldn't require network access

### ISSUE THREAD

**Issue by ojab** [appsignal/rdkafka-ruby#153]
We're building docker images with something like
```
RUN bundle package --no-install
RUN --network=none bundle install
```
And right now it fails with 
```
#20 17.43 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#20 17.43 
#20 17.43     current directory: /usr/local/bundle/gems/rdkafka-0.8.1/ext
…
#20 17.43 rake aborted!
#20 17.43 SocketError: Failed to open TCP connection to codeload.github.com:443
#20 17.43 (getaddrinfo: Temporary failure in name resolution)
…
#20 17.43 Caused by:
#20 17.43 SocketError: getaddrinfo: Temporary failure in name resolution
```
due to attempt to download librdkafka sources.

Would be nice if installation wouldn't require internet connection, since it's not uncommon situation to build stuff without network access (docker above, private gemstash instance, etcetc).

(and would be nice to be able to build it with system librdkafka if version is fine)

**Comment by wpolicarpo** [comment]
I have the same issue here and can see 2 possible solutions:

1. Allow users to pass something like [`--with-rdkafka-dir`](https://ruby-doc.org/stdlib-2.5.1/libdoc/mkmf/rdoc/MakeMakefile.html#method-i-dir_config) option via [bundle config build](https://bundler.io/man/bundle-config.1.html#BUILD-OPTIONS)
2. Allow users to override the [download URL](https://github.com/appsignal/rdkafka-ruby/blob/main/ext/Rakefile#L34) to something that's reachable within their network (or even a local file for full offline installation)

Both solutions have a downside that `librdkafka` might have a different version than the gem requires, so the gem should somehow check for the version or simply transfer the responsibility to users for doing so.

**Comment by thijsc** [comment]
I'd be happy to accept a pull request for something like this.

**Comment by thijsc** [comment]
Closing this one, there is more discussion about this going on in #157.
