### ISSUE TITLE
Installing rdkafka-ruby behind a proxy

### ISSUE THREAD

**Issue by shika-n** [appsignal/rdkafka-ruby#157]
Hi, I tried to install the gem with both `bundle install` using gemfile and `gem install rdkafka` but i'm behind a proxy and both fails. I suppose it has something to do with rake trying to fetch with https since i'm getting OpenSSL error. I tried to modify the rakefile by replacing https with http before calling open_uri and also tried to add proxy to open_uri but i'm not really sure i know what i'm exactly doing (it still outputs SSL error eventhough the link is in http). Is there a way to get around this?

More info:
- I'm developing with Rails 6 Ruby 3
- `http_proxy` variable is configured correctly since i can install other gems.
- Can't turn off proxy

The error i get when ran `gem install rdkafka` similar error when running `rake` with modified rakefile:
```    Fetching rdkafka-0.8.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing rdkafka:
    	ERROR: Failed to build gem native extension.

    current directory: /home/user/.local/share/gem/ruby/gems/rdkafka-0.8.1/ext
/usr/bin/ruby -I/usr/share/rubygems -rrubygems /home/user/.local/share/gem/ruby/gems/rake-13.0.3/exe/rake RUBYARCHDIR\=/home/user/.local/share/gem/ruby/extensions/x86_64-linux/3.0.0/rdkafka-0.8.1 RUBYLIBDIR\=/home/user/.local/share/gem/ruby/extensions/x86_64-linux/3.0.0/rdkafka-0.8.1
rake aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: unexpected message
/home/user/.local/share/gem/ruby/gems/rdkafka-0.8.1/ext/Rakefile:14:in `block in download_file_http'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:543:in `with_tempfile'
/home/user/.local/share/gem/ruby/gems/rdkafka-0.8.1/ext/Rakefile:12:in `download_file_http'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:440:in `download_file'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:54:in `block in download'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:53:in `each'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:53:in `download'
/usr/share/gems/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
/home/user/.local/share/gem/ruby/gems/rdkafka-0.8.1/ext/Rakefile:37:in `block in <top (required)>'
/home/user/.local/share/gem/ruby/gems/rake-13.0.3/exe/rake:27:in `<main>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/user/.local/share/gem/ruby/gems/rdkafka-0.8.1 for inspection.
Results logged to /home/user/.local/share/gem/ruby/extensions/x86_64-linux/3.0.0/rdkafka-0.8.1/gem_make.out
```

**Comment by clutonik** [comment]
Hi @shika-n 
Can you run below command to make sure you have proxy  environment variable available to gem:

**Command:** - gem env

If you do not see your proxy variables in the output of previous command, you can try installing this gem using below command:
Command: gem install -p http://proxy_ip:proxy_port rdkafka

If you want to stick to exporting environment variables before you run gem install, can you try exporting http_proxy, HTTP_PROXY, https_proxy, HTTPS_PROXY as well ? 

Let me know if this helps.

**Comment by shika-n** [comment]
Hi @clutonik thank you for replying,
Indeed, i did not see any proxy variables when i run `gem env`:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.15
  - RUBY VERSION: 3.0.1 (2021-04-05 patchlevel 64) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/share/gems
  - USER INSTALLATION DIRECTORY: /home/user/.local/share/gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/user/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/share/gems
     - /home/user/.local/share/gem/ruby
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install --bindir /home/user/bin"
     - :sources => ["http://rubygems.org"]
     - :concurrent_downloads => 8
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /home/user/.local/bin
     - /home/user/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
```
However, i did try to run it with both `-p` and `--http-proxy` commands which still gave me the same error message.
By running `env | grep http` i can confirm that http_proxy, HTTP_PROXY, https_proxy, and HTTPS_PROXY are all defined and have the correct value.

**Comment by clutonik** [comment]
@shika-n Can you try updating ~/.gemrc file by adding proxy en vars? You might find few examples online for this.

**Comment by shika-n** [comment]
@clutonik So i created the ~/.gemrc file and setup a basic setting with proxy as the following according to what i find online:
```
---
:backtrace: false
:bulk_threshold: 1000
:sources:
- http://rubygems.org
:update_sources: true
:verbose: true
:concurrent_downloads: 8
gem: "--user-install --bindir /home/user/bin"
http_proxy: http://proxyhost:8080
HTTP_PROXY: http://proxyhost:8080
https_proxy: http://proxyhost:8080
HTTPS_PROXY: http://proxyhost:8080
```
The proxy now shows up on `gem env`.
But no luck, still outputs the same error when i ran `gem install rdkafka`.

**Comment by clutonik** [comment]
Okay. Strange. Can you add --trace to gem install command to see more details ? Meanwhile, I will try to replicate this issue at my end.

**Comment by thijsc** [comment]
We do a separate `open` call, I'm actually not sure if that would pick up proxy env vars by default.

**Comment by shika-n** [comment]
@thijsc are there any workarounds?

**Comment by thijsc** [comment]
I was taking a look and I'm not sure. Downloading of the archive is handled by [mini_portile](https://github.com/flavorjones/mini_portile). It's not very clearly documented, but when digging around I think you should be able to set it using the `http_proxy` env var.

**Comment by shika-n** [comment]
Yes i did read about using http_proxy and did set the variable, but no luck.. The gem download itself is fine, it just the part when it's building the extension and downloading a file in the process. I'll report back here if i found anything later on.

**Comment by cdesch** [comment]
@shika-n I ran into this problem as well. This gem will not work behind a corporate proxy or with a organization CA, and there is no way to sideload `librdkafka` in anyway.

**Comment by thijsc** [comment]
We depend on [mini_portile](https://github.com/flavorjones/mini_portile) for the installation behaviour. Would be best to fix any proxy issues there.

**Comment by cdesch** [comment]
Yes, but not much luck there. I did create a monkey patched workaround:

I [forked rdkafka](https://github.com/cdesch/rdkafka-ruby) and [added](https://github.com/cdesch/rdkafka-ruby/commit/8316257165505f62ec243ed4df2c2f2bc5a290fd) the dependency locally to `ext/librdkafka-1.4.0.tar.gz` and changed: 


    recipe.files << {
        :url => "https://codeload.github.com/edenhill/librdkafka/tar.gz/v#{Rdkafka::LIBRDKAFKA_VERSION}",
        :sha256 => Rdkafka::LIBRDKAFKA_SOURCE_SHA256
     }

to:

    recipe.files << "file://#{__dir__}/librdkafka-1.4.0.tar.gz"

then added it manually to the `Gemfile` and compiled manually with `cd ext && bundle exec rake && cd ..`

it isn't pretty but it works.

**Comment by ojab** [comment]
mini_portile [use `ENV` for proxies](https://github.com/flavorjones/mini_portile/blob/863da5eeb26e4c3b8f368be25f2fbc5f60a83a30/lib/mini_portile2/mini_portile.rb#L506) and gem configuration does not change `ENV`.
So `https_proxy=foo.example.com gem install` should work.

**Comment by shika-n** [comment]
@cdesch I tried your solution with a little bit of extra work on my end and it does work! But bundler doesn't detect it as installed, but i guess that's another problem..

@ojab I did read issue 153 before posting this issue, I thought fixing this one might be faster in my case since i can access the internet. But i guess not. If issue 153 is fixed, it would defintely also fix this problem. I'm looking forward to your fix.

**Comment by cdesch** [comment]
@ojab That sort of works... but then there is a problem if you use an intermediate Package Registry (private RubyGems) and there is also a problem with self-signed Corporate CA's. This all gets more complicated with CI Pipelines and Docker Builds, so it is really nice if everything is already included in the gem out of the box and the project can do just a `bundle install`. This is why downloading the full repo into something like `./vendor/gems/rdkafka`, adding the binary `.tar.gz`, then adding it to the `Gemfile` with `path:`, and compiling is an okay workaround.

This is somewhat of a recurring problem not specific to Ruby or RubyGems but any package manager where the package it is installing has a sub-package manager or installation step that requires reaching out to a server to get a `.zip` or `.tar.gz`.

**Comment by thijsc** [comment]
What do you propose we do about this?

**Comment by mensfeld** [comment]
@cdesch can't you just fork it and inject the things you need, repack and release for offline? automating this should be fairly easy.

**Comment by thijsc** [comment]
I'm not exactly sure what to do here. We outsourced the rdkafka installation part to `mini_portile`. In principle I would say that missing installation features should be added in that project. Anybody have a different view on this?

**Comment by cdesch** [comment]
Having an embedded downloader during the installation makes sense if the version of the [`librdkafka`](https://github.com/edenhill/librdkafka) is going to be changing a lot or can be set as part of the `rdkafka-ruby` library functionality or if the dependency was a large file download. This doesn't seem to be the case for `rdkafka-ruby` as it is currently pinned on to a specific version (such as the current version `1.4.0`), so adding the extra 2.59 MB to the project for `librdkafka-1.4.0.tar.gz` doesn't seem unreasonable. 

With that said, I do not know what the roadmaps are for `rdkafka-ruby`, `librdkafka` or `kafka` and if  there will be changes that will break compatibility and require the support of multiple `librdkafka` libraries for `rdkafka-ruby` depending on the version of `kafka` the  `rdkafka-ruby` client is connecting to. It is my understanding that `kafka` is fairly mature and stable, so this might not be a risk but I would defer to others in this respect. There might be a happy medium where the downloader can pull specific versions or allow us to sideload our own library.

**Comment by shika-n** [comment]
To be honest, just having the option to at least download it manually and then set a path somewhere or put the manually downloaded source (`.tar.gz`) on the target folder (if i'm not mistaken it's `gems/rdkafka-0.8.1/ext`) would be sufficient. Unfortunately, the installer deletes the rdkafka gem folder everytime it's trying to install, so can't do that unless that behaviour can be changed. I think I did succeed once by copying and pasting quickly but i don't remember why i ended up not using that method.

If there is no problem with versions and the license for redistributing, then including the required files (either source or binary) as what @cdesch said would be a better approach since there also won't be user errors when installing.

@cdesch Thank you, i'll try it next time. I actually fixed it by copying a couple of files i found from the system gem dependencies folder to the vendor folder iirc haha.

**Comment by thijsc** [comment]
> This doesn't seem to be the case for rdkafka-ruby as it is currently pinned on to a specific version (such as the current version 1.4.0), so adding the extra 2.59 MB to the project for librdkafka-1.4.0.tar.gz doesn't seem unreasonable.

This is a viable option as far as I am concerned. I'd be more inclined to include the code than create lots of options to customize the installation process.

**Comment by thijsc** [comment]
I'm closing this one for now. If anybody has trouble with this or wants to work on improving the situation: Feel free to re-open.
