### ISSUE TITLE
`librdkafka.so` is not cached by Bundler

### ISSUE THREAD

**Issue by haines** [appsignal/rdkafka-ruby#182]
Copying `librdkafka.so` into `ext` breaks the Bundler cache; it's expected that native extensions compile artifacts to the gem's [`extension_dir`](https://github.com/rubygems/rubygems/blob/20d4957649fb7eaf4d57c220f5302ce2f4ee05ab/lib/rubygems/basic_specification.rb#L94-L108), not into `ext` directly; the result is that Bundler caches the (empty) extension directory, and does not include `ext/librdkafka.so` in the cache.

This means that reinstalling the gem fails if it is present in the Bundler cache.

To reproduce:

```ruby
# Gemfile

source "https://rubygems.org"
gem "rdkafka"
```

```console
$ bundle config set path vendor/bundle
$ bundle install
$ rm -rf vendor/bundle
$ bundle install
```

After the first install, `vendor/bundle/ruby/2.7.0/gems/rdkafka-0.11.1/ext/librdkafka.so` exists. After the second, it does not, and attempting to use the gem fails.

Related issue: https://github.com/mimemagicrb/mimemagic/issues/121
And related fix: https://github.com/mimemagicrb/mimemagic/pull/136

As you can see in the related fix it is quite easy to resolve, you just have to write the compiled artifact to the directory specified by the `RUBYARCHDIR` environment variable rather than to `ext` itself.

**Comment by thijsc** [comment]
Do you know where the files end up? Is this still within the installed gem directory?
