### ISSUE TITLE
Install ignores existing librdkafka

### ISSUE THREAD

**Issue by iftheshoefritz** [appsignal/rdkafka-ruby#184]
This gem appears to try building librdkafka regardless of its presence already. Unfortunately the librdkafka build process it uses seems to assume `/bin/bash` and breaks without it.

If the gem build process could check for the presence of `librdkafka`, it wouldn't be necessary to force users to install `bash` on their servers. In my case there is already a `librdkafka` package available for Alpine linux and I'd rather use that than install bash just for this.

**Comment by thijsc** [comment]
We don't have plans to detect librdkafka on the machine. Would using `/bin/sh` work better for you?

**Comment by iftheshoefritz** [comment]
`/bin/sh` would work for me and is more universal, I think.

**Comment by leandrofinger** [comment]
Is there a way to skip `librdkafka` build? 

I'm on a M1 Pro and it fails when running `gem install rdkafka` but I could install the librdkafka through Homebrew

**Comment by thijsc** [comment]
@mikesnare what error do you get?

**Comment by trickleup** [comment]
Does anyone have a workaround that allows them to install the gem on an M1 mac?

**Comment by clupprich** [comment]
I don't remember how I did it, but I have it installed. Must have been rather uneventful, otherwise I would probably remember. Let me see if I can refresh my memory today.

**Comment by mikesnare** [comment]
Still no resolution to this after 6 months?

**Comment by thijsc** [comment]
We don't have a use case for using a system version of the library ourselves. If you want to take on the work to make that happen I'm happy to help it get shipped!

**Comment by mikesnare** [comment]
@thijsc Fair enough, but 3 of the comments in this post are specifically about people on M1s not being able to install this gem on M1s.  I can open a separate issue for that.

**Comment by thijsc** [comment]
Also fair enough from my end then :-). I think this fell of my radar because I wasn't planning to work on the issue as it was originally opened. I'm actually going to close this one since I don't think anybody is going to push on that. Feel free to open an issue about M1 problems!
