### ISSUE TITLE
Segfaults thrown from producer running in Rails on Puma.

### ISSUE THREAD

**Issue by dezka** [appsignal/rdkafka-ruby#190]
**rdkafka-ruby version: 0.11.1
ruby 2.7.0, Rails 6, Puma 5.5.2**

We are running into a segmentation fault problem that is consistently thrown from [rd_kafka_msg_partitioner_consistent_random](https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/bindings.rb#L256) when calling `#produce` with a `partition_key` set. However the segfault situation itself is sporadic and random.

In this situation, we have an rdkafka producer running in Rails on Puma. Our running theory is that the rdkafka thread might be impacted by forking that Puma is doing. In our experience rdkafka-ruby runs into a segfault problem with forking and we’ve made it so our producers are lazy loaded (i.e. producer is starting well after the app is booted.) To try and squash this particular problem, we are running Puma config of `workers 4` and `threads 1, 1 (min, max)` to force Puma to be single threaded. This hasn’t changed a thing. But we are focusing now on how it’s the same error at the same C function every time with the same segfault message like: `Segmentation fault at 0x0000000000000000`. This hexadecimal value represents nil/null if I recall correctly. So something such as a pointer used in this C func is nil’d out by the time this runs.

Side note: [it seems we are not passing in the topic](https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/bindings.rb#L256) for the function to do the lookup upon, which is the first arg [here](https://github.com/edenhill/librdkafka/blob/0261c86228e910cc84c4c7ab74e563c121f50696/src/rdkafka.h#L2731). I don’t think this is necessarily causing the problem, but other than some other thread being killed, this is the only thing I can imagine being `nil` at the time of execution that it is complaining about. I’m sure I’m missing something here though.

Full stack trace: https://gist.github.com/dezka/92c6747bf1ca2b0a01f407a7c52f442f

**Comment by mensfeld** [comment]
This is an issue for a long time: I bypassed that in WaterDrop by detecting a fork and raising an exception because of that:

https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/producer.rb#L69

The moment rdkafka client establishes connection, it is no longer safe to fork the process without recreating the producer.

**Comment by dezka** [comment]
Hi @mensfeld, thank you for the information, glad we're not alone here. This seems to be a good solution.

Are you rescuing / recovering from the fork anywhere? (I couldn't find any such code after a brief skim) Or is this exception just notifying the user that a fork happened making the producer unable to proceed, and it's up to them on how to deal with that situation?

**Comment by thijsc** [comment]
Looking at the stacktrace it looks like this happens in `rd_kafka_msg_partitioner_consistent_random` in librdkafka itself. This could be a bug on that side.

**Comment by mensfeld** [comment]
Let me quote edenhill on this one:

>   There is no way such a forked client instance will work

ref: https://github.com/edenhill/librdkafka/blob/master/tests/0079-fork.c#L40

Though he points out that it should not crash. Nonetheless I had many problems with forks, that's why I implemented the guarding.

> Are you rescuing / recovering from the fork anywhere? (I couldn't find any such code after a brief skim) Or is this exception just notifying the user that a fork happened making the producer unable to proceed, and it's up to them on how to deal with that situation?

It is an exception. Technically WaterDrop is lazy loading the client, so you can safely initialize it before forking as long as you do not use it. If it is initialized and fork happens, the proper rdkafla client is created in the forked process. In case you would try to use a client instance that is already operating, error will be thrown.

**Comment by thijsc** [comment]
Given this I think we should add some forking detection here too. What kind of fork detection are you using in Waterdrop, comparing pids or something else?

**Comment by mensfeld** [comment]
@thijsc https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/producer.rb#L65:L69

IMHO docs should be enough and higher level producers like waterdrop and others should handle code stuff like this. Though feel free to copy if you consider useful

**Comment by thijsc** [comment]
I agree in principle, but if this can lead to segfaults I think that's outside of the contract of what a gem like this offers.

**Comment by mensfeld** [comment]
@thijsc if you tell me how you want it, I can port it.

**Comment by dezka** [comment]
I agree that the forking detection should be ported, I would expect that to be in `rdkafka-ruby` rather than pushing that off to the users of the gem.

Since we are already lazy loading our producers, I don't know if we're hitting the forking problem here though. I _think_ after digging more, we are hitting [this](https://github.com/appsignal/rdkafka-ruby/issues/15), because we are running our producers in async right now. This particular one is under very high load compared to our other producers.

I think we will have to implement an array to hold delivery handles, like [mentioned here](https://github.com/appsignal/rdkafka-ruby/issues/15#issuecomment-357247822). But I do worry that the `wait` call is going to slow things down... and in some quick testing it seems drastically slowed down. @thijsc would you be able to elaborate more on how you do this with your producers in a performant manner? Do you have a class that manages the delivery handle array making sure it doesn't leak and is cleared every so often, etc?

With that said, will there always be a segfault risk when running high load producers in async mode? It seems like we're going to have to run synchronously for higher load producers here on out.

**Comment by mensfeld** [comment]
@dezka a bit of advertisement: you may want to try waterdrop. I spent a fair amount of time making it work with buffering and thread safety while maintaining performance. Castle.io produces tens of thousand of messages per second with it and it never crashed. Castle uses a similar setup as you guys: puma + rails  + ruby 2.7.

**Comment by dezka** [comment]
> Since we are already lazy loading our producers, I don't know if we're hitting the forking problem here though. I think after digging more, we might be hitting https://github.com/appsignal/rdkafka-ruby/issues/15, because we are running our producers in async right now. This particular one is under very high load compared to our other producers.

Just to update on this, we switched over to sync producers and this didn't resolve the above segfault. I guess this may be a bug in librdkafka perhaps? Or Puma is still forking _after_ our client's are lazy loaded. Still digging around on our end.

**Comment by dezka** [comment]
@thijsc @mensfeld 

It seems we found the issue. When setting an empty `partition_key` on the produce, it recreates this segfault.

After getting some extra logging turned on recently, we were able to finally grab a payload that we think caused the crash. In a rare situation it passes an empty string to the partition key.

```
[5] pry(main)> producer.produce(topic: "test1", payload: "testmessage", partition_key: "")
/home/ubuntu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rdkafka-0.9.0/lib/rdkafka/bindings.rb:245: [BUG] Segmentation fault at 0x0000000000000068
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

**Comment by mensfeld** [comment]
Great find! This would explain why I never encountered it: https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/contracts/message.rb#L23=

I can also reproduce this issue with ruby 3.0 and 3.1.

I do recall edenhill quoting that a null key can be used in the partitioners, so my suggestion would be to use nil (works) instead of empty string for this case.
