### ISSUE TITLE
Install on M1 Mac 

### ISSUE THREAD

**Issue by JarrodFolinoFC** [appsignal/rdkafka-ruby#203]
I am trying to install and I have specified where openssl is with the following command:

`CPPFLAGS=-I/opt/homebrew/opt/openssl@1.1/include/ LDFLAGS=-L/opt/homebrew/opt/openssl@1.1/lib gem install rdkafka -v '0.10.0'`

However I get the following error:
```
========================================================================
  "_X509_get_subject_name", referenced from:
      _rd_kafka_transport_ssl_cert_verify_cb in rdkafka_ssl.o
  "_X509_new", referenced from:
      _rd_kafka_ssl_ctx_init in rdkafka_ssl.o
  "_X509_verify_cert_error_string", referenced from:
      _rd_kafka_transport_ssl_handshake in rdkafka_ssl.o
  "_d2i_PKCS12_bio", referenced from:
      _rd_kafka_conf_set_ssl_cert in rdkafka_cert.o
  "_d2i_PKCS12_fp", referenced from:
      _rd_kafka_ssl_ctx_init in rdkafka_ssl.o
  "_d2i_PrivateKey_bio", referenced from:
      _rd_kafka_conf_set_ssl_cert in rdkafka_cert.o
  "_d2i_X509_bio", referenced from:
      _rd_kafka_conf_set_ssl_cert in rdkafka_cert.o
  "_i2d_X509", referenced from:
      _rd_kafka_transport_ssl_cert_verify_cb in rdkafka_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [librdkafka.1.dylib] Error 1
make: *** [libs] Error 2
========================================================================
```

The error seems to be that it is building the native librdkafka lib based on the x86_64 architecture

Is there a way to bypass building the native lib? `brew install librdkafka` works fine

**Comment by thijsc** [comment]
Have you tried the latest version `0.12`? `0.10` was using librdkafka `1.5.0`, I do not think that version works on M1.

We've had some reports of installation issues on M1, but I haven't been able to reproduce them so far, so would love to get to the bottom of this.

**Comment by JarrodFolinoFC** [comment]
> Have you tried the latest version `0.12`? `0.10` was using librdkafka `1.5.0`, I do not think that version works on M1.
> 
> We've had some reports of installation issues on M1, but I haven't been able to reproduce them so far, so would love to get to the bottom of this.

I tried with 

- rbenv 
- ruby 2.6.0
- compiled using the x86_64 architecture
- gem version 0.12.0

And I got a similar error

>   "_LZ4F_createDecompressionContext", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>   "_LZ4F_decompress", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>   "_LZ4F_freeCompressionContext", referenced from:
>       _rd_kafka_lz4_compress in rdkafka_lz4.o
>   "_LZ4F_freeDecompressionContext", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>   "_LZ4F_getErrorName", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>       _rd_kafka_lz4_compress in rdkafka_lz4.o
>   "_LZ4F_getFrameInfo", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>   "_LZ4F_isError", referenced from:
>       _rd_kafka_lz4_decompress in rdkafka_lz4.o
>       _rd_kafka_lz4_compress in rdkafka_lz4.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [librdkafka.1.dylib] Error 1
> make: *** [libs] Error 2

Looks like I have some dependencies missing on my x86_64 binaries

**Comment by thijsc** [comment]
Odd that it seems to want to do x86 stuff. What happens if you compile librdkafka from source yourself?

**Comment by thijsc** [comment]
What do you mean with:

> compiled using the x86_64 architecture

Are you using Rosetta?

**Comment by JarrodFolinoFC** [comment]
Ok the problem was I was using a hybrid of M1 and rosetta. So I can confirm now it can work on M1 Mac when you set up the dependencies are set up correctly. I ended up using 2 versions of brew an x86 and the M1 versions. This is my setup

`
# x86 brew
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# apple silicon brew
sudo mkdir -p /opt/homebrew
sudo chown -R $(whoami):staff /opt/homebrew
cd /opt
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew

arch -arm64 brew install cmake
arch -arm64 brew install rbenv
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
arch -arm64 brew cleanup
alias ibrew='arch -x86_64 /usr/local/bin/brew'
CFLAGS="-Wno-error=implicit-function-declaration" RUBY_CONFIGURE_OPTS='--with-readline-dir=/usr/local/opt/readline/' arch -x86_64 rbenv install 2.5.9

`

**Comment by thijsc** [comment]
Thanks for letting me know!

**Comment by vicramon** [comment]
@JarrodFolinoFC I'm seeing the same thing. Are you able to share the next steps you took after setting up these environments? Did gem install simply work after that?

**Comment by ngtban** [comment]
> > Have you tried the latest version `0.12`? `0.10` was using librdkafka `1.5.0`, I do not think that version works on M1.
> > We've had some reports of installation issues on M1, but I haven't been able to reproduce them so far, so would love to get to the bottom of this.
> 
> I tried with
> 
>     * rbenv
> 
>     * ruby 2.6.0
> 
>     * compiled using the x86_64 architecture
> 
>     * gem version 0.12.0
> 
>     * librdkafka 1.9.0
> 
> 
> And I got a similar error
> 
> > "_LZ4F_createDecompressionContext", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > "_LZ4F_decompress", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > "_LZ4F_freeCompressionContext", referenced from:
> > _rd_kafka_lz4_compress in rdkafka_lz4.o
> > "_LZ4F_freeDecompressionContext", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > "_LZ4F_getErrorName", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > _rd_kafka_lz4_compress in rdkafka_lz4.o
> > "_LZ4F_getFrameInfo", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > "_LZ4F_isError", referenced from:
> > _rd_kafka_lz4_decompress in rdkafka_lz4.o
> > _rd_kafka_lz4_compress in rdkafka_lz4.o
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > make[1]: *** [librdkafka.1.dylib] Error 1
> > make: *** [libs] Error 2
> 
> Looks like I have some dependencies missing on my x86_64 binaries

Could you please give more details as to how you resolved this? I have smilar setup with both x86 and arm version of brew installed, but cannot find a way to get pass this error when installing `rdkafka-ruby`.

**Comment by ngtban** [comment]
> The dual install of homebrew might be causing this somehow. I'd guess it's looking in the wrong path for these libraries when you install. I know it works on M1 macs when everything is running fully native. Otherwise you might have to finick around with setting the right env vars.

I see. I also had both the arm and x86 version installed when I asked you, and managed to install things normally by removing both, then install back the arm version. Thanks for clarifying!
