### ISSUE TITLE
Customizing producer name for librdkafka statistics/metrics

### ISSUE THREAD

**Issue by trickleup** [appsignal/rdkafka-ruby#217]
Hi, thanks for all your work on the library.

I'm tapping librdkafka metrics via the statistics callback, which works well.

Is there a way to customize the name of the producer, that is then returned from librdkafka to the stats_callback? By default, the metrics report `rdkafka#producer-1`, `rdkafka#producer-2`, and so on, so I wonder if it's currently possible to explicitly name these to something more meaningful, so that the metrics become more useful.

Thanks!

**Comment by mensfeld** [comment]
as far as I recall you can just use `client.id`: https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/config.rb#L12

**Comment by thijsc** [comment]
That should indeed work
