### ISSUE TITLE
Rescue error_callback

### ISSUE THREAD

**Issue by kauzlaricmarko** [appsignal/rdkafka-ruby#228]
Hi, maybe a stupid question but I'm new to this gem and learning how to use it. Have one question. Is it possible to rescue and exception if passed error callback raises exception, for example:

```
  RD_KAFKA = Rdkafka::Config
  RD_KAFKA.error_callback = -> (error) { raise SomeCustomException, error}
  RD_KAFKA_CONFIG = RD_KAFKA.new({:"bootstrap.servers" => "localhost:9092"})

  begin
    producer = RD_KAFKA_CONFIG.producer
  rescue SomeCustomException => e
    producer = nil
    log_exception(e)
  end
```

**Comment by mensfeld** [comment]
No because errors are propagated in a background thread

**Comment by mensfeld** [comment]
To be more precise:

https://github.com/appsignal/rdkafka-ruby/blob/26bb67aebeff44a05b4b3f5c8f3b0819b827381a/lib/rdkafka/native_kafka.rb#L15

That is for producer. You can instrument this similar to how it is done in WaterDrop for example:

https://github.com/karafka/waterdrop#error-notifications

https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/producer.rb#L91

librdkafka most of the time produces data async and there are many errors that can occur in its threads.

Ofc some errors are inline but not all.

**Comment by kauzlaricmarko** [comment]
Thanks for your help @mensfeld, I'll close this issue now

**Comment by mensfeld** [comment]
@bbozo yes you are correct in a way ;)

So we have two things here actually:
- tracking deliveries
- monitoring errors EVEN when no deliveries (disconnects, frequent reconnects, instabilities) etc

For the first rdkafka returns you a message promise that you can query for it's state.

For the second you can connect to the error publishing layer for notifications.

You can also use what I linked above, that is waterdrop to get both (it's build on top of rdkafka). Heres an example how that looks with invalid connection port:

```ruby
producer = WaterDrop::Producer.new do |config|
  # Note invalid connection port...
  config.kafka = { 'bootstrap.servers': 'localhost:9090' }
end

producer.monitor.subscribe('error.occurred') do |event|
  error = event[:error]

  p "WaterDrop error occurred: #{error}"
end

# Run this code without Kafka cluster
loop do
  producer.produce_async(topic: 'events', payload: 'data')

  sleep(1)
end

# After you stop your Kafka cluster, you will see a lot of those:
#
# WaterDrop error occurred: Local: Broker transport failure (transport)
# WaterDrop error occurred: Local: Broker transport failure (transport)
```

**Comment by mensfeld** [comment]
You can run `wait` on handlers but they do not directly indicate a problem but rather inform you that within certain time boundaries, delivery did not went through
