### ISSUE TITLE
0.13.0.beta4 crash for not closed producers

### ISSUE THREAD

**Issue by mensfeld** [appsignal/rdkafka-ruby#234]
New issue for myself so we keep track during investigation:

1. It works until you end up not closing producer
2. Something breaks when finalizer is shutting down producers forcefully (without user closing it)

I think that due to severity (70% of times crashes) I would recommend postponing the release until we figure out what is happening. The code will work for long running processes but any case where producer is not closed may cause this.

ref https://github.com/karafka/waterdrop/actions/runs/3882428479/jobs/6622575727

**Comment by mensfeld** [comment]
Undefining `ObjectSpace.define_finalizer(...` for producer and using the one from WaterDrop seems to fix this issue.

Doing the other way around (removing the WaterDrop one and relying on rdkafka one) makes it less severe but still existing.

**Comment by mensfeld** [comment]
There is a hang on ruby exit, which indicates, that polling happens. This leads me to an educated guess, that some librdkafka resources are no longer available after poll to destroy, hence the crash.

**Comment by mensfeld** [comment]
Yeah: once destroy happens in the close method, no seg faults for the producer.

**Comment by mensfeld** [comment]
When below patch is pushed:

```ruby
module Rdkafka
  # @private
  # A wrapper around a native kafka that handles all access
  class NativeKafka
    def initialize(inner)
      @inner = inner
      @mutex = Mutex.new

      # Start thread to poll client for delivery callbacks
      @polling_thread = Thread.new do
        loop do
          Rdkafka::Bindings.rd_kafka_poll(@inner, 250)
          # Destroy consumer and exit thread if closing and the poll queue is empty
          break if Thread.current[:closing] && Rdkafka::Bindings.rd_kafka_outq_len(@inner) == 0
        end
      end

      @polling_thread.abort_on_exception = true
      @polling_thread[:closing] = false

      @closing = false
    end

    def close(object_id=nil)
      return if closed?

      # Indicate to the outside world that we are closing
      @closing = true

      # Indicate to polling thread that we're closing
      @polling_thread[:closing] = true

      @mutex.synchronize do
        return unless @inner

        # Wait for the polling thread to finish up
        @polling_thread.join

        Rdkafka::Bindings.rd_kafka_destroy(@inner)
        @inner = nil
      end
    end
  end
end
```

works as expected:

https://github.com/karafka/waterdrop/actions/runs/3883397933/jobs/6624662007

**Comment by mensfeld** [comment]
Ok. That concludes the producer. Once we agree on what to do with this, I can run regressions on consumer as they are affected by the same issue.

**Comment by mensfeld** [comment]
@thijsc do you want me to revert this to how it was?

**Comment by thijsc** [comment]
I'm taking a look later today.

**Comment by mensfeld** [comment]
My gut feeling here is that thread termination does something that causes the crashes. Ping me when you need to run it again ;)

**Comment by mensfeld** [comment]
> Supposedly joining the thread in the finalizer is not reliable.

Yes. This for sure.

> I think the issue is that if you don't explicitly destroy the native client it sometimes segfaults.

Yes and no. The GC finalizer should handle this (in theory).

**Comment by thijsc** [comment]
I've restored the implementation that seemed to work the best in #238.

**Comment by mensfeld** [comment]
Closing because I fixed this
