### ISSUE TITLE
bin/console gem executable conflicts with other gems

### ISSUE THREAD

**Issue by ziggythehamster** [appsignal/rdkafka-ruby#236]
The `gemspec` is installing bin/* as a gem executable, which makes it available in $PATH as `console` if `gem install`'ed and similarly is available as `bundle exec console` when `bundle install`'ed. This conflicts with other gems doing something similar, and is surprising behavior. I would suggest either:

1. Rename it to `bin/rdkafka_console` so it is installed with a potentially unique name.
2. Change the gemspec to instead grab `exe/*` (as long as it doesn't start with `.`), add `exe/.gitkeep`, stop publishing a bin file with the gem as a result. This is the pattern most gems are moving toward, so they can retain `bin/*` for testing/working on the gem.

**Comment by thijsc** [comment]
Thanks for reporting, I removed it.
