### ISSUE TITLE
getting missing configuration.log file error while building docker file in alpine 3.16

### ISSUE THREAD

**Issue by rajeetrautela** [appsignal/rdkafka-ruby#241]
**
<img width="773" alt="Screenshot 2023-02-08 at 3 46 57 PM" src="https://user-images.githubusercontent.com/38535972/217502040-ba9ea392-4629-46a3-b5c8-16aa0ca47d2b.png">
**
<img width="1052" alt="Screenshot 2023-02-08 at 3 47 14 PM" src="https://user-images.githubusercontent.com/38535972/217501787-b82a0370-df97-40ea-b9bf-4f540b7b700c.png">

**Comment by mensfeld** [comment]
"Cant execute bash" - do you have bash?

**Comment by mensfeld** [comment]
Alpine doesn't have a bash: https://karafka.io/docs/FAQ/#why-am-i-getting-env-cant-execute-bash-when-installing-karafka-in-an-alpine-docker
