### ISSUE TITLE
Reconsider hard locking in favour of flow control

### ISSUE THREAD

**Issue by mensfeld** [appsignal/rdkafka-ruby#260]
@thijsc there seems to be one imho critical problem with 0.13.0 approach to locking that I discovered:

because we lock poll, that can take significant amount of time, any operations that could be performed during that time that are fully safe from librdkafka perspective (pausing, seeking, etc) will be locked for an extensive period of time equal at most the polling wait time.

This can impact performance drastically upon cases like this. I think we should reconsider having the long running operations under more granular locking flow.

**Comment by mensfeld** [comment]
Actually now that I start to revisit the librdkafka docs, most of the methods are thread safe. The only thing that needs to be ensured, is that destruction (or few others) are not running in parallel. It would be much better instead of locking to keep track of usage of those (checkpoint into an array or something) and guard. That way there should be no problem with thread-safe but we should not lock (as long as we guard only the checks and not the commands)

**Comment by mensfeld** [comment]
Here's the pseudocode to do so:

```ruby
    def with_inner
      return if @inner.nil?

      caller_name = caller[0]
      @ops_in_progress << caller_name

      result = yield @inner

      p @ops_in_progress
      @ops_in_progress.delete(caller_name)

      result
    end
```

and we just need to ensure, that destroy ain't happening at the time when there's anything running

**Comment by mensfeld** [comment]
ofc caller is fairly slow, we could just use atomic int (or int via mutex) to indicate the progress without the division and guard only those that need to have 0. For example if you have poll in progress close will have to wait until the lock is released but we should start and release lock ONLY for things that collide. As far as I can see the docs, that's only closing stuff.

**Comment by mensfeld** [comment]
So my proposition here is as followed:

1. synchronized thread-safe counter on inner usage
2. a switch for `close` that will ensure that when closing, any new potentially race conditioning async methods go into a mutex
3. same mutex on close to wait for anything that is still running
4. wait on count getting to 0 and lock mutex
5. close

That way we ensure that all operations can go async BUT when we starting closing, we get into it with mutex and that no other ops are running. This will ensure, that nothing collides with `#close` and destroy and also allows to run async operations until close without heavy locking.

**Comment by thijsc** [comment]
Sounds great!

**Comment by mensfeld** [comment]
Note to self: if we expose the mutex from the native client creator to the native client, we can ensure this easily:

```ruby
def with_native
  external_mutex.synchronize { counter up }
  yield(native)
  external_mutex.synchronize { counter down }
end
```

and from the end consumer

```ruby
def close
  internal_mutex.synchronize do
    # reenter  if anything is using native
    retry if inner.counter.positive?
    
    # closing stuff here
    # since we lock the prior to inner yield and check the count, there should be no possible race condition
  end
end
```

**Comment by mensfeld** [comment]
It's done in a similar fashion here: https://github.com/karafka/waterdrop/pull/361/files - I'll copy this solution because I tested it heavily already
