### ISSUE TITLE
Support Time for timestamp attribute on produce

### ISSUE THREAD

**Issue by jurriaan** [appsignal/rdkafka-ruby#29]
I tried to produce messages with timestamps but timestamp needs to be an integer:

```
2018-03-07 13:01:19 - TypeError - no implicit conversion of Time into Integer:
        /usr/local/bundle/gems/ffi-1.9.23/lib/ffi/variadic.rb:56:in `invoke'
        /usr/local/bundle/gems/ffi-1.9.23/lib/ffi/variadic.rb:56:in `call'
        (eval):3:in `rd_kafka_producev'
```

I would expect this library to support Time instances instead of Integers (which should be millisecond unix timestamps I guess?).

**Comment by thijsc** [comment]
That's a very good point, will add support for using `Time`
