### ISSUE TITLE
Session timeout for long message processing 

### ISSUE THREAD

**Issue by mmustala** [appsignal/rdkafka-ruby#32]
Hi,

The processing time of one message can be several minutes in my app, should I define a higher session.timeout.ms in order to avoid multiple consumers processing the same partition? I really need to be sure that my messages are processed one after the other, and if there is an error in message processing it is retried until I fix the bug that causes the error.

Right now I'm seeing that sometimes the processing of next message starts before the processing of the previous message has ended. I suspect that it is due to the session timeout.

**Comment by mmustala** [comment]
After reading https://github.com/edenhill/librdkafka/issues/1817 I tried to increase the session.timeout.ms to 5 minutes (5*60*1000). Made a few consumer restarts and started to get errors for some of the consumers. 

First the errors were

```
E, [2018-06-02T08:15:01.869688 #1] ERROR -- : rdkafka: [thrd:sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/bootstr]: sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/0: 1 request(s) timed out: disconnect (average rtt 1302.354ms)
E, [2018-06-02T08:15:01.869797 #1] ERROR -- : rdkafka: [thrd:sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/bootstr]: sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/0: 1 request(s) timed out: disconnect (average rtt 1302.354ms)
E, [2018-06-02T08:15:01.869844 #1] ERROR -- : rdkafka: [thrd:sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/bootstr]: 1/1 brokers are down
```

Then it changed to 

```
E, [2018-06-02T08:17:57.571005 #1] ERROR -- : rdkafka: [thrd:sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/bootstr]: sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/0: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism SCRAM-SHA-256)
E, [2018-06-02T08:17:57.571104 #1] ERROR -- : rdkafka: [thrd:sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/bootstr]: sasl_ssl://light-wheelchair-01.srvs.cloudkafka.com:9094/0: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism SCRAM-SHA-256)
```

This lasted for 20 minutes and then I switched back to lower session timeout and after a while none of the consumers were throwing errors anymore. What I don't understand is that the consumers were not able to recover after 5 minutes, they were not able to connect the broker at all, even after 20 minutes of trying.

While increasing the session.timeout.ms, should I increase some other timeouts as well?

**Comment by thijsc** [comment]
> Right now I'm seeing that sometimes the processing of next message starts before the processing of the previous message has ended.

That should not be possible for messages in the same partition. Are you sure they are? Can you show me some code samples of what you're doing?

**Comment by mmustala** [comment]
> That should not be possible for messages in the same partition. Are you sure they are? Can you show me some code samples of what you're doing?

This was actually an issue in AWS lambda triggering. Our Kafka consumer passes the messages to AWS lambda for processing and the lambda invocation method is sometimes invoking the lambda several times. It is a quite annoying feature of that AWS API.

**Comment by thijsc** [comment]
Ok that makes sense. Can we close this one?

**Comment by mmustala** [comment]
Yeah.
