### ISSUE TITLE
How are offset commits handled?

### ISSUE THREAD

**Issue by singpolyma-shopify** [appsignal/rdkafka-ruby#34]
It looks, from reading the code, like `Consumer#each` does not do any committing -- if I call `Consumer#commit` with no arguments... what gets committed?

**Comment by thijsc** [comment]
In the config for librdkafka `enable.auto.commit` is `true` by default. This together with `auto.commit.interval.ms` will automatically commit the consumer position every 5 seconds.

I should probably add some more documentation for common cases, but in general you can find out a lot about the options and behaviour here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by singpolyma-shopify** [comment]
Oh, so it just commits whatever it has pulled off even if the consumer hasn't processed it yet?

**Comment by thijsc** [comment]
It does keep track of what gets polled, so it will never commit beyond what you popped of with `each`. If you want full control though you should use #31. Progress has been a bit stalled because of debugging #33, but once that's fixed this will roll out.
