### ISSUE TITLE
Consumer.each does not return after call to consumer.close

### ISSUE THREAD

**Issue by gaffneyc** [appsignal/rdkafka-ruby#35]
Giving rdkafka-ruby a try and I was surprised that `consumer.each` didn't return after calling `consumer.close` or `consumer.unsubscribe`.

```ruby
config = Rdkafka::Config.new({
  "bootstrap.servers": brokers,
  "security.protocol": "ssl",
  "ssl.ca.location": File.expand_path("../ca.pem", __FILE__),
  "ssl.certificate.location": File.expand_path("../client.pem", __FILE__),
  "ssl.key.location": File.expand_path("../client.key", __FILE__),
  "group.id": prefix + "rdkafka-test",
  "enable.partition.eof": false,
})

consumer = config.consumer
consumer.subscribe("topic")

trap("INT")  { consumer.close }
trap("TERM") { consumer.unsubscribe }

# Never exits
consumer.each do |m|
  puts m.inspect
end
```

It looks like `Consumer#each` is an infinite loop and never checks to see if the connection is still open or valid.

See: https://github.com/appsignal/rdkafka-ruby/blob/master/lib/rdkafka/consumer.rb#L244

**Comment by thijsc** [comment]
It would indeed make a lot of sense to stop iteration when the consumer is closed. For unsubscribing I don't think it's a good idea. It's possibly to subscribe and unsubscribe to topics at will. 

I'll make change to stop iteration when the consumer closes.

**Comment by thijsc** [comment]
Opened an issue with the `ffi` gem: https://github.com/ffi/ffi/issues/646
