### ISSUE TITLE
Verify the integrity of the downloaded 'librdkafka' tarball

### ISSUE THREAD

**Issue by koenrh** [appsignal/rdkafka-ruby#44]
I think it would be a good thing (at least from a security point of view) to verify the integrity of resources downloaded from external (potentially untrusted) sources. Think, for example, of a [CDN compromise](https://koen.io/2016/02/13/github-bug-bounty-hunting/).

It would be as easy as adding a `sha256` checksum to the file hash:

```ruby
recipe.files << {
  url: "https://github.com/edenhill/librdkafka/archive/v#{Rdkafka::LIBRDKAFKA_VERSION}.tar.gz",
  sha256: '2b96d7ed71470b0d0027bd9f0b6eb8fb68ed979f8092611c148771eb01abb72c'
}
```

Unfortunately, 'librdkafka' does not publish "official" checksums (https://github.com/edenhill/librdkafka/issues/1759), but a hash could be trivially calculated when updating the 'librdkafka' version.

**Comment by thijsc** [comment]
Totally agree with this. If librdkafka doesn't pick this up I'll generate them myself in the future.

**Comment by thijsc** [comment]
I've implemented this in #45, I'll keep this issue open until official checksums are provided.

**Comment by koenrh** [comment]
@thijsc Yes. I'll submit a PR this week.

**Comment by thijsc** [comment]
The hashes are now added to librdkafka: https://github.com/edenhill/librdkafka/releases/tag/v1.1.0
