### ISSUE TITLE
Ability to pause partitions

### ISSUE THREAD

**Issue by JHK** [appsignal/rdkafka-ruby#55]
When there is an business logic error (e.g. due to unexpected message content) I would like to make progress at least on other partitions. Therefore I propose the following pseudo-code as a draft, implementing the `pause` method on `Rdkafka::Consumer`:

```ruby
loop do
  message = consumer.poll
  process(message) if message
rescue Rdkafka::RdkafkaError => e
  raise unless e.is_partition_eof?
rescue => e
  consumer.pause(message.topic, message.partition)
end
```

For reference:
 * [Kafka consumer docs on `pause`](https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#pause-java.util.Collection-)
 * [corresponding `librdkafka` binding](https://docs.confluent.io/3.2.1/clients/librdkafka/rdkafka_8h.html#a293cb2aac290c157702d3b82f5c14fce)

**Comment by thijsc** [comment]
Good idea, will add a binding for pause. I assume the code ⬆️ is an example of how you could use it, and not something you'd want to add to the gem?

**Comment by JHK** [comment]
Exactly, this is just pseudo code I came up with to explain the use-case. Can probably be used in the documentation of this feature though.
