### ISSUE TITLE
New release with changes in master

### ISSUE THREAD

**Issue by mjkillough** [appsignal/rdkafka-ruby#66]
Would it be possible to make a new release from master? I'm particularly interested in the changes from #31, which haven't been released yet.

We're currently depending on `rdkafka-ruby` using a git dependency in our Gem file, but would prefer to fetch it from RubyGems as we start to use it in more services.

Thanks again for doing all the work to maintain this! It's a huge help. :-)

**Comment by thijsc** [comment]
Yes, will make on later today.

**Comment by thijsc** [comment]
The latest changes were released in 0.4.2.

**Comment by mjkillough** [comment]
Thanks a lot!
