### ISSUE TITLE
How to enable “gzip” function at AMI Linux2 os?

### ISSUE THREAD

**Issue by dypublic** [appsignal/rdkafka-ruby#76]
I try to use fluentd in AMI Linux2 os.
And I need use kafka output plugin for push messages to kafka.
The "gzip" should be good for performance for pushing.
So I use gem to install the rdkaka-ruby.
But the rdkafka don't enable gzip at install/compile stage.
So when I add "gzip" option into fluentd config, it will say "wrong value for compress.type".
How could I enable the gzip feature at "gem install rdkafka" step? Or other way to enable the gzip function?
I do have zlib-devel on the linux, "Package zlib-devel-1.2.8-7.18.amzn1.x86_64 already installed and latest version".

**Comment by thijsc** [comment]
It sounds like rdkafka wasn't compiled with zlib support, I am not sure why. Maybe an extra configure option is needed here: https://github.com/appsignal/rdkafka-ruby/blob/master/ext/Rakefile#L35

**Comment by thijsc** [comment]
Feel free to reopen if you find out anything.
