### ISSUE TITLE
Useless pending delivery waiting upon unsendable message

### ISSUE THREAD

**Issue by mensfeld** [appsignal/rdkafka-ruby#80]
Given a setup:

- `message.send.max.retries` set to `2`
- `bootstrap.servers` set to `invalid:9002`

What happens upon producing and waiting is:

```
E, [2019-08-07T18:01:48.096491 #23972] ERROR -- : rdkafka: [thrd:invalid:9092/bootstrap]: invalid:9092/bootstrap: Failed to resolve 'invalid:9092': Name or service not known (after 21ms in state CONNECT)
E, [2019-08-07T18:01:48.096606 #23972] ERROR -- : rdkafka: [thrd:invalid:9092/bootstrap]: invalid:9092/bootstrap: Failed to resolve 'invalid:9092': Name or service not known (after 21ms in state CONNECT)
E, [2019-08-07T18:01:48.096654 #23972] ERROR -- : rdkafka: [thrd:invalid:9092/bootstrap]: 1/1 brokers are down
```

After that, `rdkafka` will not retry to send again, while `rdkafka-ruby` will wait (here: https://github.com/appsignal/rdkafka-ruby/blob/master/lib/rdkafka/producer/delivery_handle.rb#L49) until the default timeout of 60 seconds.

Even if the `invalid` url would be resolved by the DNS, the `librdkafka` won't retry sending it again as it reached the max number of attempts.

code:

```ruby
config = {:"bootstrap.servers" => "invalid:9092"}
delivery_handles = []
producer = Rdkafka::Config.new(config).producer

producer.produce(
  topic:   "ruby-test-topic",
  payload: "Payload" * 1000,
  key:     "Key"
).wait
```

There is no point in waiting when we've used max retry attempts.

What I would suggest doing instead: raise a `RdKafka` error when we've run out of attempts.

**Comment by mensfeld** [comment]
The errors are not due to the delivery failure upon dns resolve but come from the connection failure although I still believe the case is valid.

**Comment by thijsc** [comment]
librdafka does not tell us directly if this is the case. I believe the way to handle this is using https://docs.confluent.io/2.0.0/clients/librdkafka/rdkafka_8h.html#ace721ef3b7c22d0c111ec747ef039a90.

Some errors are fatal, and you could get a callback for them where you could fail some messages. That's not wrapped in this library yet, the only way to see it is checking the error logs. We have monitoring on the amount of produced messages to pick up on delivery errors.

It would be really nice to do something with the error callbacks, not sure yet what that should look like exactly.

**Comment by thijsc** [comment]
I'm planning to work on adding some kind of global error hook soon. @mensfeld have you worked on this already?

**Comment by mensfeld** [comment]
@thijsc no. I plan to once I have stable test suit for Karafka where I could add this case. I am getting closer though. 2.0 is already on Github and started working on the specs today.

**Comment by thijsc** [comment]
A global error hook is being added in #161
