### ISSUE TITLE
Provide way to use a different method of partitioning

### ISSUE THREAD

**Issue by thijsc** [appsignal/rdkafka-ruby#89]
Other Ruby kafka clients have a feature where you can provide a separate key that's used just for partitioning. There is a partitioning callback in the C api that could be used to achieve a similar effect.

**Comment by dasch** [comment]
Has there been any updates on this? As an alternative, is there an API for getting the partition count of a topic? That could be used to replicate the `partition_key` functionality in Racecar.

**Comment by thijsc** [comment]
I'm still working on getting the test suite stable in #98, as soon as that's fixed I plan to pick up this one. Not sure if there's a way to reliably get the partition count.

**Comment by dasch** [comment]
Has there been an update on the partition count problem?

**Comment by thijsc** [comment]
This hasn't made it to the top of my list. We finally fixed the build issues, so we can move forward with adding some new features now.

**Comment by dasch** [comment]
Thanks! This is currently blocking us from upgrading many of our consumers to Racecar v2 (which uses rdkafka-ruby) because messages would not be assigned to the same partitions that they used to, and we're using compaction.

**Comment by Adithya-copart** [comment]
@thijsc I took a look at the available options last night. Here is what I found:

1. `librdkafka` internal metadata cache mentioned in the [documentation](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#metadata). I don't think this is exposed.
2. The [metadata API](https://github.com/edenhill/librdkafka/blob/c8fd8e682bb79e756920176b34051f18e7c8c006/src/rdkafka.h#L3870-L4052) exposes the partition info.
3. There is a [old comment](https://github.com/edenhill/librdkafka/issues/1158#issuecomment-305423028) that `librdkafka` is willing to expose a built-in partitioner but I don't think it is implemented.

**Comment by Adithya-copart** [comment]
I'm using [this example](https://github.com/edenhill/librdkafka/blob/c8fd8e682bb79e756920176b34051f18e7c8c006/examples/rdkafka_example.c#L789-L864) to see if I can come up with working code.

I'm stuck at passing the right nested Metadata `FFI::Struct`. Will create a draft PR in the next two or three days.

**Comment by thijsc** [comment]
The previously used Kafka gem has a feature where you can provide a separate `key` and `partition_key`. `key` is used as the actual key, while `partition_key` is only used to determine the partition and is not actually added to the message.

I think we can replicate this behaviour using https://docs.confluent.io/current/clients/librdkafka/rdkafka_8h.html#abfc790b5e36c56ea6d79fdc32c57becf

This lets us set a partitioner callback that gets called with the message, it could look at an optional partition key field to determine the wanted partition.

This is the type of behaviour you require right @dasch?

**Comment by dasch** [comment]
Either replicating the partition key semantics or providing the means for clients to do so themselves, yes. I think the latter is fine if this library does not want to have an opinionated partitioning layer. But that would likely require a way to query the partition count for a topic - I’m not sure if the callback approach suffices without the overhead of an “envelope” object.

**Comment by Adithya-copart** [comment]
@thijsc I did not look into the partitioner callback earlier. I went with the logic that `rdkafka-ruby` supports `key` and `partition` in `Producer#produce`, so  clients can pass the appropriate `partition` based on their partitioning logic. The partition count necessary for this computation can use `Producer#partitions_count`.

Let me know your thoughts on which approach you think suits better.

@dasch I also noticed that `rdkafka-ruby` is using [RD_KAFKA_PARTITION_UA](https://github.com/edenhill/librdkafka/blob/c8fd8e682bb79e756920176b34051f18e7c8c006/src/rdkafka.h#L2667-L2673) in the [producer](https://github.com/appsignal/rdkafka-ruby/blob/e5c7261e3f2637554a5c12b924be297d7dca1328/lib/rdkafka/producer.rb#L82-L84) when a `partition` is not specified. This should use consistent random partitioner in `librdkafka` when a `key` is present as per https://github.com/edenhill/librdkafka/pull/548.

**Comment by Adithya-copart** [comment]
It looks like `librdkafka` guarantees that messages with the same key are committed to the same partition. I will test this and verify.

The use-cases to be addressed in the fix are:
1. `partition_key` exists but not a message `key`.
2. [Precedence](https://github.com/zendesk/ruby-kafka/blob/6bd4121f15ef3b8f1ed05783ed44971b647ea3dc/lib/kafka/partitioner.rb#L26) is to the `partition_key` when a `key` is also present.

Rather than having `librdkafka` call a ruby method in these scenarios, it may be better if `Producer#produce` accepts a `partition_key` and use the same consistent random partitioner function in `librdkafka`.

**Comment by dasch** [comment]
My problem is that I need to provide a backwards compatible partition assignment algorithm in order to avoid really nasty problems when people upgrade from ruby-kafka to rdkafka-ruby. So it’s not enough that the functionality is there, it either needs to match that of ruby-kafka, or there needs to be a way to specify the exact partitioning scheme (with access to the partition count).

**Comment by thijsc** [comment]
> Rather than having librdkafka call a ruby method in these scenarios, it may be better if Producer#produce accepts a partition_key and use the same consistent random partitioner function in librdkafka.

That's the idea, I don't think we should offer a callback to the user of the library. We can implement it ourselves to look at `partition_key` if it's available.

**Comment by Adithya-copart** [comment]
I noticed that the partitioning logic in [ruby-kafka ](https://github.com/zendesk/ruby-kafka/blob/6bd4121f15ef3b8f1ed05783ed44971b647ea3dc/lib/kafka/partitioner.rb#L31) is similar to [librdkafka](https://github.com/edenhill/librdkafka/blob/c8fd8e682bb79e756920176b34051f18e7c8c006/src/rdkafka_msg.c#L837). This logic could be from the Java client.

However, I'll make sure that backward-compatibility is guaranteed by exposing the `partition_count`.

**Comment by Adithya-copart** [comment]
@thijsc Opened  https://github.com/appsignal/rdkafka-ruby/pull/110 with the changes.

It exposes the partition count and accepts a partition key along with the existing parameters.

**Comment by dasch** [comment]
Awesome!

**Comment by thijsc** [comment]
Added in #110.
